import LegalLayout from "@/app/components/LegalLayout";

export const metadata = { title: "Other Policies — Synaptara" };

export default function OtherPoliciesPage() {
  return (
    <LegalLayout
      title="Other Policies"
      lastUpdated="July 1, 2026"
      intro="This page consolidates additional policies governing specific aspects of your use of Synaptara. These policies apply alongside our Terms of Use and Privacy Policy. Please review each section carefully."
      sections={[
        {
          heading: "Acceptable Use Policy",
          body: [
            "Synaptara is designed to support legitimate academic and professional research. You agree to use the Service only for lawful purposes and in a manner that does not infringe the rights of others or restrict their use of the Service.",
            "Prohibited uses include: scraping or bulk-downloading content without prior written consent; using automated tools to access the Service in a manner that exceeds reasonable personal use; using the Service to generate, distribute, or promote misinformation, harmful content, or content that violates applicable law; attempting to reverse-engineer, decompile, or tamper with the Service or its underlying infrastructure.",
            "We reserve the right to suspend or terminate accounts that we determine, in our sole discretion, are in violation of this Acceptable Use Policy.",
          ],
        },
        {
          heading: "Research Content Policy",
          body: [
            "Synaptara aggregates and summarises publicly available research content from third-party sources. We do not claim ownership of the underlying papers, articles, or publications sourced from providers such as arXiv, PubMed, OpenAI, and DeepMind.",
            "Summaries, citations, and analysis generated by the Service are provided for informational purposes only and should not be relied upon as a substitute for reading the original source material. You are responsible for verifying the accuracy and suitability of any research content before use in professional, academic, or commercial contexts.",
          ],
        },
        {
          heading: "AI-Generated Content Policy",
          body: [
            "Some features of Synaptara use artificial intelligence to summarise, analyse, and surface research content. AI-generated outputs may contain errors, omissions, or inaccuracies. We do not warrant the completeness or accuracy of any AI-generated content.",
            "You agree not to present AI-generated summaries from Synaptara as original authorship without appropriate attribution. Where applicable, always cite the primary source material.",
          ],
        },
        {
          heading: "Third-Party Sources and Links Policy",
          body: "The Service provides access to content hosted by third-party providers. Synaptara is not responsible for the accuracy, availability, or legality of content on third-party platforms. Links to external sites do not constitute an endorsement of those sites or their content. Your interactions with third-party sites are governed by those sites' own terms and privacy policies.",
        },
        {
          heading: "Account Suspension and Termination Policy",
          body: [
            "Synaptara reserves the right to suspend or permanently terminate your account at our discretion for violations of our Terms of Use, Acceptable Use Policy, or any other applicable policy, or for non-payment of applicable subscription fees.",
            "If your account is suspended, you will be notified by email where reasonably practicable. You may appeal a suspension by contacting legal@synaptara.com within 14 days of the notice.",
          ],
        },
        {
          heading: "DMCA and Copyright Infringement Policy",
          body: [
            "We respect the intellectual property rights of others. If you believe any content available through the Service infringes your copyright, please send a written notice to legal@synaptara.com including: (a) a description of the copyrighted work; (b) the URL or location of the allegedly infringing material; (c) your contact information; and (d) a statement of good-faith belief that the use is not authorised.",
            "We will review all valid DMCA notices and take appropriate action, which may include removing the infringing content and, where applicable, terminating repeat infringers' accounts.",
          ],
        },
        {
          heading: "Updates to These Policies",
          body: "We may update any of the policies on this page at any time. Significant changes will be communicated to registered users via email. Continued use of the Service after changes are posted constitutes acceptance of the updated policies.",
        },
      ]}
    />
  );
}
